//
//  GarageError.swift
//  GarageStorage
//
//  Created by Brian Arnold on 11/16/25.
//

import Foundation


extension Garage {
    
    /// The domain for errors generated by GarageStorage.
    ///
    /// Provided for backward compatibility. Use ``GarageError.errorDomain`` instead.
    public static let errorDomain = GarageError.errorDomain
}

/// Errors that may be thrown from GarageStorage.
///
/// Errors conform to NSError, and have the "GarageStorage" error domain and localized descriptions.
public enum GarageError: Error, CustomNSError {
    
    /// This error is thrown when an internal _retrieve_ call is not expected to fail, such as when deleting an object already deleted, or not yet parked.
    /// No error is thrown when one of the public `retrieve` calls are made; in those cases, a nil object or empty array are returned.
    case failedToRetrieveObject(String, String)
    
    /// This error is thrown when a Core Data Object is missing its storage data.
    /// The conditions for throwing this error are extremely rare, such as memory corruption while parking an object.
    case storageDataIsNil(String)
    
    /// This error is thrown when using `park`, `retrieve`, or `delete` on an object that doesn't conform to `Identifiable` or `Hashable`.
    case missingConformance(String)
    
    // MARK: CustomNSError conformance
    
    /// The domain for errors generated by GarageStorage.
    public static var errorDomain: String { "GarageStorage" }
    
    /// The `UserInfo` contains the string for `localizedDescription`.
    public var errorUserInfo: [String : Any] {
        var userInfo: [String: Any] = [:]
        switch self {
        case .failedToRetrieveObject(let typeName, let identifier):
            userInfo[NSLocalizedDescriptionKey] = "Failed to retrieve object of type: \(typeName) with identifier: \(identifier)"
            
        case .storageDataIsNil(let typeName):
            userInfo[NSLocalizedDescriptionKey] = "CoreDataObject.gsData is nil for type: \(typeName)"

        case .missingConformance(let typeName):
            userInfo[NSLocalizedDescriptionKey] = "Missing Identifiable or Hashable conformance for type: \(typeName)"
        }
        
        
        return userInfo
    }
}

extension Decoder {
    
    /// Returns a `DecodingError.dataCorrupted` with a debug description that refers to a missing `Identifiable` reference.
    /// We use this instead of a GarageError enum in order to capture the codingPath from the decoder, so that we have a better idea where it came from.
    func missingIdentifiableReference(typeName: String = "unknown", identifier: String = "missing") -> Error {
        let description = "Missing Identifiable reference of type: \(typeName) with id: \(identifier)"
        let context = DecodingError.Context(codingPath: self.codingPath, debugDescription: description)
        return DecodingError.dataCorrupted(context)
    }
}

// MARK: internal Objective-C compatibility

extension GarageError {
    
    // For Objective-C, continue using NSError directly.
    // Support will be deprecated then removed in future library updates.
    static func makeError(_ description: String) -> Error {
        let userInfo = [NSLocalizedDescriptionKey : description]
        return NSError(domain: Garage.errorDomain, code: -1, userInfo: userInfo)
    }
}

